Getting rid of Name(s) deleted hack
Gear61/Random-Name-Picker pull request #122
Opened 2020-02-10 10:10 UTC by ALAA999

2020-02-13 04:09 UTC, Gear61 requested changes
Can you add a screenshot/video demo of both cases as well?

2020-02-13 04:09 UTC, Gear61 commented on app/src/main/res/values/edit_name_list_strings.xml
> +    <string name="names_deleted">%d instances of \"%s\" deleted from the list</string>
```suggestion
    <string name="names_deleted">%d instances of \"%s\" deleted from the list.</string>
```

2020-02-13 07:54 UTC, ALAA999 commented
![Screenshot_20200213-095234](https://user-images.githubusercontent.com/32240376/74412765-d36c7880-4e46-11ea-9591-f944edca6e9b.png)
![Screenshot_20200213-095248](https://user-images.githubusercontent.com/32240376/74412771-d7989600-4e46-11ea-9275-b7d90a775eb9.png)

2020-02-13 07:55 UTC, ALAA999 commented on app/src/main/res/values/edit_name_list_strings.xml
> +    <string name="names_deleted">%d instances of \"%s\" deleted from the list</string>
Sure!

2020-02-22 19:44 UTC, Gear61 approved these changes
Awesome!

2020-02-22 19:44 UTC, Gear61 commented on app/src/main/res/values/edit_name_list_strings.xml
> +    <string name="names_deleted">%d instances of \"%s\" deleted from the list</string>
Can you add the period at the end? We'll be good to go after that.

2020-02-22 19:45 UTC, merged