Initial theme mode
Gear61/Random-Name-Picker pull request #139
Opened 2020-05-07 02:13 UTC by mohammedhemaid

The video of the feature:
https://photos.app.goo.gl/UXhRZQybrh5bKHVz5

For the fragments recreation, we can use the old instance but that requires more work:
1- override onSavedInstanceState and save the currentViewId for the selected fragment.
2- on recreation  in OnCreate we will assign the homepageFragment and settingsFragment in the 
 HomepageFragmentController with the old instance from the FragmentManager.
3- In the BottomNavigationView we will need to select the selected fragment.

2020-05-08 06:34 UTC, Gear61 requested changes
This looks great! The code makes a lot of sense to me, and it's quite clean overall.

Anyways, after watching the video, it's a pretty bad experience when you toggle the dark mode switch and you get taken back to the homepage. Does onSavedInstanceState() get called when the app restarts? We could theoretically call getActivity() and call some sort of setter on it so that when it restarts (savedInstanceState Bundle is non-null in onCreate()), it knows to tab to the settings fragment. Is this feasible? Let's try to make this user experience work, even if we have to write some messy code. We can always wrap the code to make it not as messy, haha.

2020-05-08 06:34 UTC, Gear61 commented on app/src/main/java/com/randomappsinc/studentpicker/settings/SettingsFragment.java
> +                Switch DarkModeToggle = secondCell.findViewById(R.id.shake_toggle);
```suggestion
                Switch darkModeToggle = secondCell.findViewById(R.id.shake_toggle);
```

2020-05-08 06:34 UTC, Gear61 commented on app/src/main/res/values/settings_strings.xml
> +    <string name="dark_Mode">Dark Mode</string>
```suggestion
    <string name="dark_mode">Dark mode</string>
```

2020-05-08 14:01 UTC, mohammedhemaid commented
The video of the update:
https://photos.app.goo.gl/BjGTYgdb5Vqq2pwf9

2020-05-08 14:15 UTC, mohammedhemaid commented
@Gear61 
I was worried about the messy code hahaha,  now I used the old instance and get the id of the latest selected view, it now working but the code still needs some cleaning.

2020-05-10 01:38 UTC, Gear61 approved these changes
Good first step! I just have some small comments you can dress in the next pull request.

2020-05-10 01:38 UTC, Gear61 commented on app/src/main/java/com/randomappsinc/studentpicker/home/HomeActivity.java
> +        if (savedInstanceState == null) {
We should annotate savedInstanceState as @Nullable.

2020-05-10 01:38 UTC, Gear61 commented on app/src/main/java/com/randomappsinc/studentpicker/home/HomeActivity.java
> +    private static final String PREVIOUS_SELECTED_ID = "previousSelectedId";
This is more descriptive IMHO.
```suggestion
    private static final String PREVIOUSLY_SELECTED_PAGE_ID = "previouslySelectedPageId";
```

2020-05-10 01:38 UTC, Gear61 commented on app/src/main/java/com/randomappsinc/studentpicker/home/HomepageFragmentController.java
> +    }
```suggestion
    int getCurrentViewId() {
        return currentViewId;
    }
```

2020-05-10 01:38 UTC, merged