master
Gear61/Random-Name-Picker pull request #53
Opened 2019-10-31 11:45 UTC by mohammedhemaid

I am just added a splash screen

2019-10-31 21:50 UTC, Gear61 requested changes
This is a good start! It looks like there's some weird formatting stuff going on, so the main thing is to fix that. Also, feel free to increase the version code in the app level's build.gradle as well.

2019-10-31 21:50 UTC, Gear61 commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
We don't need constraint layout for this. I try to avoid constraint layout since I find its API to be confusing.

2019-10-31 21:50 UTC, Gear61 commented on app/src/main/AndroidManifest.xml
> -<manifest
Can you undo all your AndroidManifest changes minus the new splash activity? There's a lot of new labels on activities and stuff too; we need to keep this code review focused.

2019-10-31 21:50 UTC, Gear61 commented on app/src/main/res/drawable/splash_screen.xml
> +                android:src="@drawable/splash_logo"
nit: Make the spacing between src and gravity consistent. Looks like we just need to indent back a tab?

2019-10-31 21:50 UTC, Gear61 commented on app/app.iml
> +    <orderEntry type="library" name="Gradle: androidx.constraintlayout:constraintlayout-solver:1.1.3@jar" level="project" />
Hopefully these disappear once we remove constraint layout.

2019-10-31 23:20 UTC, mohammedhemaid commented
Sorry for these mistakes I will work hard on my Git and Github to be familiar with it.

2019-11-01 05:35 UTC, Gear61 commented
@mohammedhemaid No need to apologize, the main point of code review is to make mistakes and learn from it!

2019-11-01 05:41 UTC, Gear61 requested changes
Thanks for responding to the feedback! A couple minor formatting changes and we should be good.

2019-11-01 05:41 UTC, Gear61 commented on app/src/main/AndroidManifest.xml
> +xmlns:android="http://schemas.android.com/apk/res/android"
nit: Move the spacing to where it was before.

2019-11-01 05:41 UTC, Gear61 commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
nit: Remove the extra spaces at the end for this line and the next one.

2019-11-01 05:41 UTC, Gear61 commented on app/src/main/AndroidManifest.xml
>          android:theme="@style/AppTheme">
nit: Add newline after this line.

2019-11-01 05:41 UTC, Gear61 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".init.SplashActivity"
nit: Move android:name to the next line.

2019-11-01 05:41 UTC, Gear61 commented on app/src/main/AndroidManifest.xml
> +
nit: Delete the newline here and the spaces after MAIN and LAUNCHER.

2019-11-01 05:41 UTC, Gear61 commented on app/src/main/AndroidManifest.xml
> +            android:windowSoftInputMode="adjustResize">
Ahhh, I realize now that all of these rearrangements are for alphabetizing. That makes sense; good change :)

2019-11-01 05:41 UTC, Gear61 commented on app/src/main/res/drawable/splash_screen.xml
> +                android:src="@drawable/splash_logo"
Reminder to follow up on this.

2019-11-03 00:12 UTC, Gear61 approved these changes
Looks good! Thanks for doing this!

2019-11-03 00:13 UTC, merged